Repository dimitriBouteille/wp-orm, pull requests merged in 2025-03, with the labels that each got.

#101 Add support for WordPress Multisite
  src/Models/Meta/UserMeta.php
  src/Models/Multisite/Blog.php
  src/Models/Multisite/BlogVersion.php
  src/Models/Multisite/RegistrationLog.php
  src/Models/Multisite/Signup.php
  src/Models/Multisite/Site.php
  src/Models/Multisite/SiteMeta.php
  src/Models/User.php
  src/Orm/AbstractModel.php
  src/Orm/Database.php
Labels: enhancement, development, v4

#132 Add multisite tests
  README.md
  src/Models/Meta/UserMeta.php
  src/Models/Multisite/Blog.php
  src/Models/Multisite/BlogVersion.php
  src/Models/Multisite/RegistrationLog.php
  src/Models/Multisite/Signup.php
  src/Models/Multisite/Site.php
  src/Models/Multisite/SiteMeta.php
  src/Models/User.php
  src/Orm/AbstractModel.php
  src/Orm/Database.php
Labels: development, v4

#130 📦 Release 4.3.0
  .github/workflows/tests.yml
  README.md
  src/Models/Meta/UserMeta.php
  src/Models/Multisite/Blog.php
  src/Models/Multisite/BlogVersion.php
  src/Models/Multisite/RegistrationLog.php
  src/Models/Multisite/Signup.php
  src/Models/Multisite/Site.php
  src/Models/Multisite/SiteMeta.php
  src/Models/User.php
  src/Orm/AbstractModel.php
  src/Orm/Database.php
Labels: ready to deploy, v4
