Repository dimitriBouteille/wp-orm, pull requests merged in 2025-02, with the labels that each got.

#116 [FEATURE] Add coverage to unit tests
  .github/workflows/tests.yml
  .gitignore
  README.md
  composer.json
  phpunit.xml
  tests/Unit/Concerns/HasMetasTest.php
  tests/Unit/Models/CommentTest.php
  tests/Unit/Models/CustomCommentTest.php
  tests/Unit/Models/CustomPostTest.php
  tests/Unit/Orm/DatabaseTest.php
  tests/Unit/Scopes/CustomModelTypeScopeTest.php
Labels: enhancement, development, v4

#119 🔧 CI : Run WordPress tests with coverage and use parallel coverage
  .github/workflows/tests.yml
  composer.json
  phpunit-wp.xml
Labels: enhancement, ready to deploy

#125 📦 Release 4.2.0
  composer.json
  renovate.json
  src/Concerns/HasMetas.php
  tests/WordPress/Concerns/HasMetasTest.php
Labels: ready to deploy, v4
