Repository dimitriBouteille/wp-orm, pull requests merged in 2025-01, with the labels that each got.

#111 Prunable / MassPrunable trait not working - undefined event() function
  .github/workflows/tests.yml
  composer.json
  config/scripts/install-wp-tests.sh
  src/Orm/AbstractModel.php
  src/helpers.php
  tests/WordPress/Concerns/PrunableTest.php
Labels: bug, development

#112 Release v4.1.0
  .github/workflows/tests.yml
  composer.json
  config/scripts/install-wp-tests.sh
  src/Orm/AbstractModel.php
  src/helpers.php
  tests/WordPress/Concerns/PrunableTest.php
Labels: v4

#114 Fix two typos in tests
  tests/WordPress/Models/OptionTest.php
  tests/WordPress/Orm/AbstractModelWithCustomTableTest.php
  tests/WordPress/TestCase.php
Labels: ready to deploy, v4

#117 [DOC] Pinpoint autoloader loading in README
  README.md
Labels: documentation, ready to deploy, v4

#115 Improve tests workflow
  .github/workflows/tests.yml
Labels: v4
